{% set name = "imagepy" %}
{% set version = "0.22" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8929304896edcb200134641e3e5f509de107918bad6d963c64b6e39ffe814949" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_value }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - scikit-image >=0.14.0
    - shapely >=1.0
    - wxpython >=4.0
    - numba >=0.29
    - pypubsub >=4.0
    - pandas >=0.23
    - xlrd >=1.1.0
    - xlwt >=1.3.0
    - openpyxl >=2.5.3
    - pydicom >=1.0
    - markdown >=2.6
    - numpy-stl >=2.7

test:
  imports:
    - imagepy

about:
  home: https://github.com/Image-Py/imagepy
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: interactive python image-processing plugin framework
  description: |
    Image process framework based on plugin like imagej.
    It is easy to glue with any libraries based on numpy.
    Such as scipy.ndimage, scikit-image, opencv, simpleitk, mayavi...
  doc_url: 'https://github.com/Image-Py/imagepy'
  dev_url: 'https://github.com/Image-Py/imagepy'

extra:
  recipe-maintainers: 
    - yxdragon
