travis:
  secure:
    BINSTAR_TOKEN: MZcek3uXKF4wQ21dljUkgGWs0VrNTm/Pb2Q/cTARfVSDb6L+JWfMQ1A84Mn48QVZ6zDKnBVmcIo3CTMbEo/HTxcC2kcwNtGZH+cpCTcJBjdyN3S58Cu1MdjhFznHOfUfL08QBkBJQiByqpjB4a88XNPAxoKP04roxPbOGovlOEbwM8bZ8dVRVSBMdHlj3VPt7L0dh7AJP5D/qV4tfDtZxWofZNQlKOPlHKGAxGWA17/Puc2e7JmDIChhq1Zgd5XfTou5+dVH2KnM3hRpRLRF+MI24QPxJo19D1e41nOIs4lqneJ/fJGaBA1Jjgc9sHK6Yd6xEEYUphQYUcOw5RRllk/5/4b019XHr2rxA5RttG4ti6nNQWo7HbhLrkq2n/8O4vCA3NCMH/sEC1/NQMPyvYTWCe/Z2CI4fnXvm8+5fRdFeeahEJ9Kndv/SSFkSmLSv3x4y0vK9lSFt/NKkH3Y03FHTSismYjsccpHPzj7GDkxqt9alKd1yf7C8AhQFTIT0e7dMpW1ALVOaqCk+U299P6kBA9hgJeQ/u2F9xY6rVZhf++mRMQz3GjNlaJca9mYzryPrSCCdk8BfEVflkcM5F58XHnjUqBozd+Vir8XA4zxSyZyqrDSYcsteShRz3t0uNCy2xbcz+Bug3+AWlL1AQydagbMnzP76+hNKhVoLJc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
