travis:
  secure:
    BINSTAR_TOKEN: dHk/l89OhtA0BWqKjPrHwMTNmiEFWJZnTMqRHQLBg67wQGUApkUuCMfmOZyhFAFlh6x6gY1RLqtc3+ZxIHdS27QCdSaLPO+5zgZxi00eSiFfajfqeK8ge6z/HU5bYcj6Igmf+/cYWx1vtiKicq7MYKVkysiNOdcx4ZmNYIr/jonPGwX5pomWVhbVBPpiLhIehxIiNbYPCSt3fDV5c/UpsWpQAlP5JYqsy25CeyM3cNsZS65y0exx+U0xUaJlHKLMmkdpAohf1apSylqTnHQJHozIejIg/WbPCGIgVlolBOHhr3UEWwN9qfWQV0uZA4h8btPk+4EGetDNESHsHywSGmPcuKXt9m/MY4LqpKG2TkPynNQksGTR+zg6Ec3fOl8yUHk0M2RNZoWIAX+mHrq4ERohDz2DrbeoLC+IPYb0HZWdpKF3hGa6/CIs2fpG8Qann/vXi+G/BNiHQszuAiMvaeroYyhu1oTzZp0XK92IooYgVnaw77NVSmIfQgs7Inec6hH/EEfOqM+rxJJGXMm972qW8puj8WdwWEXHArPmv2Gf0Rc2WOqvb228nWOOZ7r7c+DJ01ESjo6bBTok609hlEtdklV5ka7Mv3w8nLqB4FrtKms69OTknNA6YnOHcItpZ8DklUEB17Wz/V33WzN4BJ/0RHLv2s7STvTJEJuDX94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
