travis:
  secure:
    BINSTAR_TOKEN: FjpxarFwoFlNe69XuLpovW/bCObXLbnwHDpiTIuiZk5oLsZlsO7Okty28hu2CqtZ98QHEkpMets0Ke9XsMhan/EiaoGbxK03M4hgeiJgd8p/J3wkoQFD57wRYrHN/MaK6WEcnaifHCUOmAmTpikW0XOuGirO1RYxebhDKWCbjLttXndMUljofnq5fYLbV9orRRch1PHqEO69Bhb/c0mMXuvTQRrNA4Lrte/G/+3A45MOGoMRGbAsWK1iK9GInNgXW0iKlVBwAKD1fevAFNi3+nxF1EcKXkNuuFGgz8+LvtLaWwOvy9CESgpsQGyBisCiaUUJ4Wg9TTen3+qa5M8m5/RlvSWuF3t3z4wPMJ4otNdHoaPQeNVP6DmvPqTmU7+jAsLwUuvA04Hyu4ZhgYzY/51n1fbvzWxxkxGEFFWC7pvs7o5BlAiml4UpXO3nBmqWqpciLAz08zd4lX4QBWj2scZQFgKZPDWZ1w9//MXpC/8pv3Vfw+GJb1mVeUcDpxcyCR0VoXBx8KCFD0yyy9B8HuF6C+06tK44tLhaFtWOlT4b1tZMf3WQuxixPu6zHUCDe6KPch8WVtDOWkxtofyox6I2zLC7oy6IfiNEXPQiSTwfaF5ULJQvEzI9SCsZ59vz/DNhESCp3/nqMgQDS1XF/NfslrygxxkMEQWb03Xp6xw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
